# Form implementation generated from reading ui file 'gui.ui'
#
# Created by: PyQt6 UI code generator 6.9.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(277, 278)
        self.label_title = QtWidgets.QLabel(parent=Dialog)
        self.label_title.setGeometry(QtCore.QRect(30, 10, 131, 21))
        self.label_title.setObjectName("label_title")
        self.Input_ID = QtWidgets.QLineEdit(parent=Dialog)
        self.Input_ID.setGeometry(QtCore.QRect(60, 40, 181, 41))
        self.Input_ID.setObjectName("Input_ID")
        self.Button_submit = QtWidgets.QPushButton(parent=Dialog)
        self.Button_submit.setGeometry(QtCore.QRect(30, 170, 231, 51))
        self.Button_submit.setObjectName("Button_submit")
        self.label_ID = QtWidgets.QLabel(parent=Dialog)
        self.label_ID.setGeometry(QtCore.QRect(30, 50, 47, 13))
        self.label_ID.setObjectName("label_ID")
        self.label_candidate = QtWidgets.QLabel(parent=Dialog)
        self.label_candidate.setGeometry(QtCore.QRect(60, 100, 101, 16))
        self.label_candidate.setObjectName("label_candidate")
        self.Button_Jane = QtWidgets.QRadioButton(parent=Dialog)
        self.Button_Jane.setGeometry(QtCore.QRect(60, 120, 82, 17))
        self.Button_Jane.setObjectName("Button_Jane")
        self.buttonGroup = QtWidgets.QButtonGroup(Dialog)
        self.buttonGroup.setObjectName("buttonGroup")
        self.buttonGroup.addButton(self.Button_Jane)
        self.Button_John = QtWidgets.QRadioButton(parent=Dialog)
        self.Button_John.setGeometry(QtCore.QRect(60, 140, 82, 17))
        self.Button_John.setObjectName("Button_John")
        self.buttonGroup.addButton(self.Button_John)
        self.label_Text = QtWidgets.QLabel(parent=Dialog)
        self.label_Text.setGeometry(QtCore.QRect(30, 230, 231, 20))
        self.label_Text.setObjectName("label_Text")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label_title.setText(_translate("Dialog", "Voting Application"))
        self.Button_submit.setText(_translate("Dialog", "SUBMIT VOTE"))
        self.label_ID.setText(_translate("Dialog", "ID"))
        self.label_candidate.setText(_translate("Dialog", "CANDIDATES"))
        self.Button_Jane.setText(_translate("Dialog", "Jane"))
        self.Button_John.setText(_translate("Dialog", "John"))
        self.label_Text.setText(_translate("Dialog", "TextLabel"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec())
